### PR TITLE
Implement `git pull --rebase before push`

### PR DESCRIPTION
**Pull request by bdovh**

### CODE REVIEW

**Comment by notfilippo** [comment]
Hey, sorry for the wait. Could you make it as an option of the action? See #12 for implementation details.

**Comment by bdovh** [comment]
do you mean a boolean switch?

**Comment by notfilippo** [comment]
Yes, exactly

**Review by devenes — COMMENTED** [review]
It would be great if we could use it in an option and add information to the README file. Please let me know if there's anything I can help with.

**Comment by notfilippo** [comment]
Implemented in #23

**Pull request closed without merging**
